<?php
/**
 * Auto generated by prado-cli.php on 2013-11-13 04:49:16.
 */
class TblClassifica extends TActiveRecord
{
	const TABLE='tbl_classifica';

	public $id;
	public $classifica;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>