<?php
/**
 * Auto generated by prado-cli.php on 2013-11-13 04:49:16.
 */
class TblGrips extends TActiveRecord
{
	const TABLE='tbl_grips';

	public $id;
	public $tbl_brands_id;
	public $model;
	public $price;
	public $note;
	
	public $brand_name;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>