<?php
/**
 * Auto generated by prado-cli.php on 2013-11-14 12:52:48.
 */
class TblStringType extends TActiveRecord
{
	const TABLE='tbl_string_type';

	public $id;
	public $description;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>