<?php
/**
 * Auto generated by prado-cli.php on 2013-11-14 02:53:30.
 */
class TblStringingMachinesType extends TActiveRecord
{
	const TABLE='tbl_stringing_machine_type';

	public $id;
	public $description;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>