<?php
/**
 * Auto generated by prado-cli.php on 2013-11-18 02:01:32.
 */
class TblStringingJobType extends TActiveRecord
{
	const TABLE='tbl_stringing_job_type';

	public $id;
	public $description;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>