<?php
/**
 * Auto generated by prado-cli.php on 2013-11-12 10:34:10.
 */
class TblUsers extends TActiveRecord
{
	const TABLE='tbl_users';

	public $id;
	public $type_user_id;
	public $username;
	public $password;
	public $active;
	public $confirm_code;
	public $name;
	public $surname;
	public $email;
	public $telephone;
	public $mobile_telephone;
	public $fax;
	public $cost;
	public $date_insert;
	public $tbl_currency_unit_id;
	public $tbl_weight_unit_id;
	public $piva;
	
	public $currency_unit;
	public $weight_unit;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>