<?php
/**
 * Auto generated by prado-cli.php on 2013-11-15 02:24:01.
 */
class TblGripSize extends TActiveRecord
{
	const TABLE='tbl_grip_size';

	public $id;
	public $europe_size;
	public $usa_size;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>