<?php
/**
 * Auto generated by prado-cli.php on 2013-11-14 12:50:38.
 */
class TblGauges extends TActiveRecord
{
	const TABLE='tbl_gauges';

	public $id;
	public $usa;
	public $diameter;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>