<?php
/**
 * Auto generated by prado-cli.php on 2013-11-14 12:18:43.
 */
class TblStrings extends TActiveRecord
{
	const TABLE='tbl_strings';

	public $id;
	public $tbl_brands_id;
	public $tbl_gauges_id;
	public $tbl_string_type_id;
	public $model;
	public $code;
	public $exact_gauge;
	
	
	public $brand_name;
	public $gauge_desc;
	public $string_type;
	public $price;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>