<?php
/**
 * Auto generated by prado-cli.php on 2013-11-18 05:27:15.
 */
class TblWeightUnit extends TActiveRecord
{
	const TABLE='tbl_weight_unit';

	public $id;
	public $description;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>