<?php
/**
 * Auto generated by prado-cli.php on 2013-11-20 10:49:16.
 */
class LogRacquetUser extends TActiveRecord
{
	const TABLE='log_racquet_user';

	public $id;
	public $id_tbl_racquet_user;
	public $weight_unstrung;
	public $weight_strung;
	public $balance;
	public $swingweight;
	public $stiffness;
	public $date_modify;
	public $note;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>