<?php
/**
 * Auto generated by prado-cli.php on 2013-11-15 09:58:32.
 */
class RelStringerStringingMachine extends TActiveRecord
{
	const TABLE='rel_stringer_stringing_machine';

	public $id_stringer;
	public $id_stringing_machine;
	public $serial;
	public $date_buy;
	public $date_calibration;
	public $note;
	public $default;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>