<?php
/**
 * Auto generated by prado-cli.php on 2013-11-13 09:42:22.
 */
class RelStringerCustomer extends TActiveRecord
{
	const TABLE='rel_stringer_customer';

	public $id_stringer;
	public $id_customer;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>