<?php
/**
 * Auto generated by prado-cli.php on 2013-11-12 10:28:09.
 */
class TblBrands extends TActiveRecord
{
	const TABLE='tbl_brands';

	public $id;
	public $description;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>