<?php
/**
 * Auto generated by prado-cli.php on 2013-11-15 10:54:33.
 */
class TblRacquetsPattern extends TActiveRecord
{
	const TABLE='tbl_racquets_pattern';

	public $id;
	public $description;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>