package it.napalm.stringtools.object;

import java.math.BigDecimal;
import java.util.Date;

/**
 * LogRacquetUser generated by hbm2java
 */
public class LogRacquetUser implements java.io.Serializable {

	private LogRacquetUserId id;
	private BigDecimal weightUnstrung;
	private BigDecimal weightStrung;
	private BigDecimal balance;
	private BigDecimal swingweight;
	private BigDecimal stiffness;
	private Date dateModify;
	private String note;

	public LogRacquetUser() {
	}

	public LogRacquetUser(LogRacquetUserId id, BigDecimal weightUnstrung,
			BigDecimal weightStrung, BigDecimal balance,
			BigDecimal swingweight, BigDecimal stiffness) {
		this.id = id;
		this.weightUnstrung = weightUnstrung;
		this.weightStrung = weightStrung;
		this.balance = balance;
		this.swingweight = swingweight;
		this.stiffness = stiffness;
	}

	public LogRacquetUser(LogRacquetUserId id, BigDecimal weightUnstrung,
			BigDecimal weightStrung, BigDecimal balance,
			BigDecimal swingweight, BigDecimal stiffness, Date dateModify,
			String note) {
		this.id = id;
		this.weightUnstrung = weightUnstrung;
		this.weightStrung = weightStrung;
		this.balance = balance;
		this.swingweight = swingweight;
		this.stiffness = stiffness;
		this.dateModify = dateModify;
		this.note = note;
	}

	public LogRacquetUserId getId() {
		return this.id;
	}

	public void setId(LogRacquetUserId id) {
		this.id = id;
	}

	public BigDecimal getWeightUnstrung() {
		return this.weightUnstrung;
	}

	public void setWeightUnstrung(BigDecimal weightUnstrung) {
		this.weightUnstrung = weightUnstrung;
	}

	public BigDecimal getWeightStrung() {
		return this.weightStrung;
	}

	public void setWeightStrung(BigDecimal weightStrung) {
		this.weightStrung = weightStrung;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public BigDecimal getSwingweight() {
		return this.swingweight;
	}

	public void setSwingweight(BigDecimal swingweight) {
		this.swingweight = swingweight;
	}

	public BigDecimal getStiffness() {
		return this.stiffness;
	}

	public void setStiffness(BigDecimal stiffness) {
		this.stiffness = stiffness;
	}

	public Date getDateModify() {
		return this.dateModify;
	}

	public void setDateModify(Date dateModify) {
		this.dateModify = dateModify;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
