package it.napalm.stringtools.object;

/**
 * LogRacquetUserId generated by hbm2java
 */
public class LogRacquetUserId implements java.io.Serializable {

	private int id;
	private int idTblRacquetUser;

	public LogRacquetUserId() {
	}

	public LogRacquetUserId(int id, int idTblRacquetUser) {
		this.id = id;
		this.idTblRacquetUser = idTblRacquetUser;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getIdTblRacquetUser() {
		return this.idTblRacquetUser;
	}

	public void setIdTblRacquetUser(int idTblRacquetUser) {
		this.idTblRacquetUser = idTblRacquetUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LogRacquetUserId))
			return false;
		LogRacquetUserId castOther = (LogRacquetUserId) other;

		return (this.getId() == castOther.getId())
				&& (this.getIdTblRacquetUser() == castOther
						.getIdTblRacquetUser());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getIdTblRacquetUser();
		return result;
	}

}
