package it.napalm.stringtools.object;

/**
 * RelStringerStringingMachineId generated by hbm2java
 */
public class RelStringerStringingMachineId implements java.io.Serializable {

	private String idStringer;
	private String idStringingMachine;

	public RelStringerStringingMachineId() {
	}

	public RelStringerStringingMachineId(String idStringer,
			String idStringingMachine) {
		this.idStringer = idStringer;
		this.idStringingMachine = idStringingMachine;
	}

	public String getIdStringer() {
		return this.idStringer;
	}

	public void setIdStringer(String idStringer) {
		this.idStringer = idStringer;
	}

	public String getIdStringingMachine() {
		return this.idStringingMachine;
	}

	public void setIdStringingMachine(String idStringingMachine) {
		this.idStringingMachine = idStringingMachine;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelStringerStringingMachineId))
			return false;
		RelStringerStringingMachineId castOther = (RelStringerStringingMachineId) other;

		return ((this.getIdStringer() == castOther.getIdStringer()) || (this
				.getIdStringer() != null && castOther.getIdStringer() != null && this
				.getIdStringer().equals(castOther.getIdStringer())))
				&& ((this.getIdStringingMachine() == castOther
						.getIdStringingMachine()) || (this
						.getIdStringingMachine() != null
						&& castOther.getIdStringingMachine() != null && this
						.getIdStringingMachine().equals(
								castOther.getIdStringingMachine())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdStringer() == null ? 0 : this.getIdStringer()
						.hashCode());
		result = 37
				* result
				+ (getIdStringingMachine() == null ? 0 : this
						.getIdStringingMachine().hashCode());
		return result;
	}

}
