package it.napalm.stringtools.object;
// Generated 12-dic-2013 10.48.19 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TblOvergrips generated by hbm2java
 */
public class TblOvergrips implements java.io.Serializable {

	private Integer id;
	private int idTblBrands;
	private String model;
	private double price;
	private String note;

	public TblOvergrips() {
	}

	public TblOvergrips(int idTblBrands, String model, double price) {
		this.idTblBrands = idTblBrands;
		this.model = model;
		this.price = price;
	}

	public TblOvergrips(int idTblBrands, String model, double price,
			String note) {
		this.idTblBrands = idTblBrands;
		this.model = model;
		this.price = price;
		this.note = note;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdTblBrands() {
		return this.idTblBrands;
	}

	public void setIdTblBrands(int idTblBrands) {
		this.idTblBrands = idTblBrands;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double d) {
		this.price = d;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
