package it.napalm.stringtools.object;
// Generated 12-dic-2013 10.48.19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblStrings generated by hbm2java
 */
public class TblStrings implements java.io.Serializable {

	private Integer id;
	private int tblGauges;
	private int tblBrands;
	private int tblStringType;
	private String model;
	private String code;
	private double exactGauge;
	private double price;
	private Set tblStringingJobsesForTblStringsIdCross = new HashSet(0);
	private Set relStringPrices = new HashSet(0);
	private Set tblStringingJobsesForTblStringsIdMain = new HashSet(0);

	public TblStrings() {
	}

	public TblStrings(int tblGauges, int tblBrands,
			int tblStringType, String model, String code,
			double exactGauge) {
		this.tblGauges = tblGauges;
		this.tblBrands = tblBrands;
		this.tblStringType = tblStringType;
		this.model = model;
		this.code = code;
		this.exactGauge = exactGauge;
	}

	public TblStrings(int tblGauges, int tblBrands,
			int tblStringType, String model, String code,
			double exactGauge, Set tblStringingJobsesForTblStringsIdCross,
			Set relStringPrices, Set tblStringingJobsesForTblStringsIdMain) {
		this.tblGauges = tblGauges;
		this.tblBrands = tblBrands;
		this.tblStringType = tblStringType;
		this.model = model;
		this.code = code;
		this.exactGauge = exactGauge;
		this.tblStringingJobsesForTblStringsIdCross = tblStringingJobsesForTblStringsIdCross;
		this.relStringPrices = relStringPrices;
		this.tblStringingJobsesForTblStringsIdMain = tblStringingJobsesForTblStringsIdMain;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getTblGauges() {
		return this.tblGauges;
	}

	public void setTblGauges(int tblGauges) {
		this.tblGauges = tblGauges;
	}

	public int getTblBrands() {
		return this.tblBrands;
	}

	public void setTblBrands(int tblBrands) {
		this.tblBrands = tblBrands;
	}

	public int getTblStringType() {
		return this.tblStringType;
	}

	public void setTblStringType(int tblStringType) {
		this.tblStringType = tblStringType;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public double getExactGauge() {
		return this.exactGauge;
	}

	public void setExactGauge(double exactGauge) {
		this.exactGauge = exactGauge;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
