package it.napalm.stringtools.object;
// Generated 12-dic-2013 10.48.19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblTypeUser generated by hbm2java
 */
public class TblTypeUser implements java.io.Serializable {

	private Integer id;
	private String description;
	private Set tblUserses = new HashSet(0);

	public TblTypeUser() {
	}

	public TblTypeUser(String description) {
		this.description = description;
	}

	public TblTypeUser(String description, Set tblUserses) {
		this.description = description;
		this.tblUserses = tblUserses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getTblUserses() {
		return this.tblUserses;
	}

	public void setTblUserses(Set tblUserses) {
		this.tblUserses = tblUserses;
	}

}
