package it.napalm.stringtools.object;
// Generated 12-dic-2013 10.48.19 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblUsers generated by hbm2java
 */
public class TblUsers implements java.io.Serializable {

	private Integer id;
	private int tblTypeUser;
	private String username;
	private String password;
	private int active;
	private String confirmCode;
	private String name;
	private String surname;
	private String email;
	private String telephone;
	private String mobileTelephone;
	private String fax;
	private double cost;
	private Date dateInsert;
	private int tblCurrencyUnitId;
	private int tblWeightUnitId;
	private String piva;
	private Set relStringPrices = new HashSet(0);
	private Set tblUsersesForIdStringer = new HashSet(0);
	private Set tblRacquetsUsers = new HashSet(0);
	private Set tblUsersesForIdCustomer = new HashSet(0);

	public TblUsers() {
	}

	public TblUsers(int tblTypeUser, String username, String password,
			int active, String confirmCode, int tblCurrencyUnitId,
			int tblWeightUnitId, String piva) {
		this.tblTypeUser = tblTypeUser;
		this.username = username;
		this.password = password;
		this.active = active;
		this.confirmCode = confirmCode;
		this.tblCurrencyUnitId = tblCurrencyUnitId;
		this.tblWeightUnitId = tblWeightUnitId;
		this.piva = piva;
	}

	public TblUsers(int tblTypeUser, String username, String password,
			int active, String confirmCode, String name, String surname,
			String email, String telephone, String mobileTelephone, String fax,
			double cost, Date dateInsert, int tblCurrencyUnitId,
			int tblWeightUnitId, String piva, Set relStringPrices,
			Set tblUsersesForIdStringer, Set tblRacquetsUsers,
			Set tblUsersesForIdCustomer) {
		this.tblTypeUser = tblTypeUser;
		this.username = username;
		this.password = password;
		this.active = active;
		this.confirmCode = confirmCode;
		this.name = name;
		this.surname = surname;
		this.email = email;
		this.telephone = telephone;
		this.mobileTelephone = mobileTelephone;
		this.fax = fax;
		this.cost = cost;
		this.dateInsert = dateInsert;
		this.tblCurrencyUnitId = tblCurrencyUnitId;
		this.tblWeightUnitId = tblWeightUnitId;
		this.piva = piva;
		this.relStringPrices = relStringPrices;
		this.tblUsersesForIdStringer = tblUsersesForIdStringer;
		this.tblRacquetsUsers = tblRacquetsUsers;
		this.tblUsersesForIdCustomer = tblUsersesForIdCustomer;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getTblTypeUser() {
		return this.tblTypeUser;
	}

	public void setTblTypeUser(int tblTypeUser) {
		this.tblTypeUser = tblTypeUser;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	public String getConfirmCode() {
		return this.confirmCode;
	}

	public void setConfirmCode(String confirmCode) {
		this.confirmCode = confirmCode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getMobileTelephone() {
		return this.mobileTelephone;
	}

	public void setMobileTelephone(String mobileTelephone) {
		this.mobileTelephone = mobileTelephone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public double getCost() {
		return this.cost;
	}

	public void setCost(double d) {
		this.cost = d;
	}

	public Date getDateInsert() {
		return this.dateInsert;
	}

	public void setDateInsert(Date dateInsert) {
		this.dateInsert = dateInsert;
	}

	public int getTblCurrencyUnitId() {
		return this.tblCurrencyUnitId;
	}

	public void setTblCurrencyUnitId(int tblCurrencyUnitId) {
		this.tblCurrencyUnitId = tblCurrencyUnitId;
	}

	public int getTblWeightUnitId() {
		return this.tblWeightUnitId;
	}

	public void setTblWeightUnitId(int tblWeightUnitId) {
		this.tblWeightUnitId = tblWeightUnitId;
	}

	public String getPiva() {
		return this.piva;
	}

	public void setPiva(String piva) {
		this.piva = piva;
	}

	public Set getRelStringPrices() {
		return this.relStringPrices;
	}

	public void setRelStringPrices(Set relStringPrices) {
		this.relStringPrices = relStringPrices;
	}

	public Set getTblUsersesForIdStringer() {
		return this.tblUsersesForIdStringer;
	}

	public void setTblUsersesForIdStringer(Set tblUsersesForIdStringer) {
		this.tblUsersesForIdStringer = tblUsersesForIdStringer;
	}

	public Set getTblRacquetsUsers() {
		return this.tblRacquetsUsers;
	}

	public void setTblRacquetsUsers(Set tblRacquetsUsers) {
		this.tblRacquetsUsers = tblRacquetsUsers;
	}

	public Set getTblUsersesForIdCustomer() {
		return this.tblUsersesForIdCustomer;
	}

	public void setTblUsersesForIdCustomer(Set tblUsersesForIdCustomer) {
		this.tblUsersesForIdCustomer = tblUsersesForIdCustomer;
	}

}
