package it.napalm.stringtools.object;

/**
 * RelStringPriceId generated by hbm2java
 */
public class RelStringPriceId implements java.io.Serializable {

	private int idStrings;
	private int idStringer;

	public RelStringPriceId() {
	}

	public RelStringPriceId(int idStrings, int idStringer) {
		this.idStrings = idStrings;
		this.idStringer = idStringer;
	}

	public int getIdStrings() {
		return this.idStrings;
	}

	public void setIdStrings(int idStrings) {
		this.idStrings = idStrings;
	}

	public int getIdStringer() {
		return this.idStringer;
	}

	public void setIdStringer(int idStringer) {
		this.idStringer = idStringer;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelStringPriceId))
			return false;
		RelStringPriceId castOther = (RelStringPriceId) other;

		return (this.getIdStrings() == castOther.getIdStrings())
				&& (this.getIdStringer() == castOther.getIdStringer());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdStrings();
		result = 37 * result + this.getIdStringer();
		return result;
	}

}
