package it.napalm.stringtools.object;
// Generated 12-dic-2013 10.48.19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblBrands generated by hbm2java
 */
public class TblBrands implements java.io.Serializable {

	private Integer id;
	private String description;
	private Set tblStringses = new HashSet(0);
	private Set tblStringingMachineses = new HashSet(0);
	private Set tblRacquetses = new HashSet(0);
	private Set tblGripses = new HashSet(0);
	private Set tblOvergripses = new HashSet(0);

	public TblBrands() {
	}

	public TblBrands(String description, Set tblStringses,
			Set tblStringingMachineses, Set tblRacquetses, Set tblGripses,
			Set tblOvergripses) {
		this.description = description;
		this.tblStringses = tblStringses;
		this.tblStringingMachineses = tblStringingMachineses;
		this.tblRacquetses = tblRacquetses;
		this.tblGripses = tblGripses;
		this.tblOvergripses = tblOvergripses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getTblStringses() {
		return this.tblStringses;
	}

	public void setTblStringses(Set tblStringses) {
		this.tblStringses = tblStringses;
	}

	public Set getTblStringingMachineses() {
		return this.tblStringingMachineses;
	}

	public void setTblStringingMachineses(Set tblStringingMachineses) {
		this.tblStringingMachineses = tblStringingMachineses;
	}

	public Set getTblRacquetses() {
		return this.tblRacquetses;
	}

	public void setTblRacquetses(Set tblRacquetses) {
		this.tblRacquetses = tblRacquetses;
	}

	public Set getTblGripses() {
		return this.tblGripses;
	}

	public void setTblGripses(Set tblGripses) {
		this.tblGripses = tblGripses;
	}

	public Set getTblOvergripses() {
		return this.tblOvergripses;
	}

	public void setTblOvergripses(Set tblOvergripses) {
		this.tblOvergripses = tblOvergripses;
	}
	
	@Override
    public String toString() {
        return this.description;
    }


}
