package it.napalm.stringtools.object;
// Generated 12-dic-2013 10.48.19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblGripSize generated by hbm2java
 */
public class TblGripSize implements java.io.Serializable {

	private int id;
	private String europeSize;
	private String usaSize;
	private Set tblRacquetsUsers = new HashSet(0);

	public TblGripSize() {
	}

	public TblGripSize(int id) {
		this.id = id;
	}

	public TblGripSize(int id, String europeSize, String usaSize,
			Set tblRacquetsUsers) {
		this.id = id;
		this.europeSize = europeSize;
		this.usaSize = usaSize;
		this.tblRacquetsUsers = tblRacquetsUsers;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getEuropeSize() {
		return this.europeSize;
	}

	public void setEuropeSize(String europeSize) {
		this.europeSize = europeSize;
	}

	public String getUsaSize() {
		return this.usaSize;
	}

	public void setUsaSize(String usaSize) {
		this.usaSize = usaSize;
	}

	public Set getTblRacquetsUsers() {
		return this.tblRacquetsUsers;
	}

	public void setTblRacquetsUsers(Set tblRacquetsUsers) {
		this.tblRacquetsUsers = tblRacquetsUsers;
	}

}
