package it.napalm.stringtools.object;
// Generated 12-dic-2013 10.48.19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblGauges generated by hbm2java
 */
public class TblGauges implements java.io.Serializable {

	private Integer id;
	private String usa;
	private String diameter;
	private Set tblStringses = new HashSet(0);

	public TblGauges() {
	}

	public TblGauges(String usa, String diameter) {
		this.usa = usa;
		this.diameter = diameter;
	}

	public TblGauges(String usa, String diameter, Set tblStringses) {
		this.usa = usa;
		this.diameter = diameter;
		this.tblStringses = tblStringses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsa() {
		return this.usa;
	}

	public void setUsa(String usa) {
		this.usa = usa;
	}

	public String getDiameter() {
		return this.diameter;
	}

	public void setDiameter(String diameter) {
		this.diameter = diameter;
	}
	
	public String getDescription() {
		return getUsa() + "(" + getDiameter() + ")";
	}
	
	public String toString() {
		return getUsa() + "(" + getDiameter() + ")";
	}
}
