package it.napalm.stringtools.object;
// Generated 12-dic-2013 10.48.19 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TblOvergrips generated by hbm2java
 */
public class TblOvergrips implements java.io.Serializable {

	private Integer id;
	private TblBrands tblBrands;
	private String model;
	private BigDecimal price;
	private String note;

	public TblOvergrips() {
	}

	public TblOvergrips(TblBrands tblBrands, String model, BigDecimal price) {
		this.tblBrands = tblBrands;
		this.model = model;
		this.price = price;
	}

	public TblOvergrips(TblBrands tblBrands, String model, BigDecimal price,
			String note) {
		this.tblBrands = tblBrands;
		this.model = model;
		this.price = price;
		this.note = note;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TblBrands getTblBrands() {
		return this.tblBrands;
	}

	public void setTblBrands(TblBrands tblBrands) {
		this.tblBrands = tblBrands;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
