package it.napalm.stringtools.object;
// Generated 12-dic-2013 10.48.19 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblRacquetsUser generated by hbm2java
 */
public class TblRacquetsUser implements java.io.Serializable {

	private Integer id;
	private int tbl_racquets_id;
	private int tbl_grip_size_id;
	private int tbl_users_id;
	private String serial;
	private double weightUnstrung;
	private double weightStrung;
	private double balance;
	private double swingweight;
	private double stiffness;
	private Date dateBuy;
	private String note;
	private int active;
	private Set tblStringingJobses = new HashSet(0);

	public TblRacquetsUser() {
	}

	public TblRacquetsUser(int tbl_racquets_id, int tbl_grip_size_id,
			int tbl_users_id, String serial, double weightUnstrung,
			double weightStrung, double balance,
			double swingweight, double stiffness, int active) {
		this.tbl_racquets_id = tbl_racquets_id;
		this.tbl_grip_size_id = tbl_grip_size_id;
		this.tbl_users_id = tbl_users_id;
		this.serial = serial;
		this.weightUnstrung = weightUnstrung;
		this.weightStrung = weightStrung;
		this.balance = balance;
		this.swingweight = swingweight;
		this.stiffness = stiffness;
		this.active = active;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getTblRacquets() {
		return this.tbl_racquets_id;
	}

	public void setTblRacquets(int tbl_racquets_id) {
		this.tbl_racquets_id = tbl_racquets_id;
	}

	public int getTblGripSize() {
		return this.tbl_grip_size_id;
	}

	public void setTblGripSize(int tbl_grip_size_id) {
		this.tbl_grip_size_id = tbl_grip_size_id;
	}

	public int getTblUsers() {
		return this.tbl_users_id;
	}

	public void setTblUsers(int tbl_users_id) {
		this.tbl_users_id = tbl_users_id;
	}

	public String getSerial() {
		return this.serial;
	}

	public void setSerial(String serial) {
		this.serial = serial;
	}

	public double getWeightUnstrung() {
		return this.weightUnstrung;
	}

	public void setWeightUnstrung(double d) {
		this.weightUnstrung = d;
	}

	public double getWeightStrung() {
		return this.weightStrung;
	}

	public void setWeightStrung(double d) {
		this.weightStrung = d;
	}

	public double getBalance() {
		return this.balance;
	}

	public void setBalance(double d) {
		this.balance = d;
	}

	public double getSwingweight() {
		return this.swingweight;
	}

	public void setSwingweight(double d) {
		this.swingweight = d;
	}

	public double getStiffness() {
		return this.stiffness;
	}

	public void setStiffness(double d) {
		this.stiffness = d;
	}

	public Date getDateBuy() {
		return this.dateBuy;
	}

	public void setDateBuy(Date dateBuy) {
		this.dateBuy = dateBuy;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public int getActive() {
		return this.active;
	}

	public void setActive(int active) {
		this.active = active;
	}

	public Set getTblStringingJobses() {
		return this.tblStringingJobses;
	}

	public void setTblStringingJobses(Set tblStringingJobses) {
		this.tblStringingJobses = tblStringingJobses;
	}

}
