package it.napalm.stringtools.object;
// Generated 12-dic-2013 10.48.19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblStringingMachines generated by hbm2java
 */
public class TblStringingMachines implements java.io.Serializable {

	private Integer id;
	private TblBrands tblBrands;
	private TblStringingMachineType tblStringingMachineType;
	private String model;
	private Set tblStringingJobses = new HashSet(0);

	public TblStringingMachines() {
	}

	public TblStringingMachines(TblBrands tblBrands,
			TblStringingMachineType tblStringingMachineType) {
		this.tblBrands = tblBrands;
		this.tblStringingMachineType = tblStringingMachineType;
	}

	public TblStringingMachines(TblBrands tblBrands,
			TblStringingMachineType tblStringingMachineType, String model,
			Set tblStringingJobses) {
		this.tblBrands = tblBrands;
		this.tblStringingMachineType = tblStringingMachineType;
		this.model = model;
		this.tblStringingJobses = tblStringingJobses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TblBrands getTblBrands() {
		return this.tblBrands;
	}

	public void setTblBrands(TblBrands tblBrands) {
		this.tblBrands = tblBrands;
	}

	public TblStringingMachineType getTblStringingMachineType() {
		return this.tblStringingMachineType;
	}

	public void setTblStringingMachineType(
			TblStringingMachineType tblStringingMachineType) {
		this.tblStringingMachineType = tblStringingMachineType;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public Set getTblStringingJobses() {
		return this.tblStringingJobses;
	}

	public void setTblStringingJobses(Set tblStringingJobses) {
		this.tblStringingJobses = tblStringingJobses;
	}

}
