package it.napalm.stringtools.object;
// Generated 12-dic-2013 10.48.19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblStringingJobType generated by hbm2java
 */
public class TblStringingJobType implements java.io.Serializable {

	private Integer id;
	private String description;
	private Set tblStringingJobses = new HashSet(0);

	public TblStringingJobType() {
	}

	public TblStringingJobType(String description) {
		this.description = description;
	}

	public TblStringingJobType(String description, Set tblStringingJobses) {
		this.description = description;
		this.tblStringingJobses = tblStringingJobses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getTblStringingJobses() {
		return this.tblStringingJobses;
	}

	public void setTblStringingJobses(Set tblStringingJobses) {
		this.tblStringingJobses = tblStringingJobses;
	}

}
